import Link from "next/link"
import "./globals.css"
import "./clojure.css"
import { Space_Grotesk } from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider"
import { Analytics } from "@/components/analytics"
import { ModeToggle } from "@/components/mode-toggle"
import {Footer} from "@/components/footer";

const spaceGrotesk = Space_Grotesk({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}


export default function RootLayout({ children }: RootLayoutProps) {
  const linkClassName = "underline-offset-4 hover:underline outline-none hover:text-orange-600 dark:hover:text-yellow-600"
  return (
    <html lang="en">
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50 ${spaceGrotesk.className}`}
      >
        <ThemeProvider attribute="class"
                       defaultTheme="system"
                       enableSystem>
          <div className="max-w-2xl mx-auto py-10 px-4 h-full">
            <header>
              <div className="flex items-center justify-between">
                <nav className="mr-auto text-sm font-medium space-x-6">
                  <Link href="/" className={linkClassName}>Home</Link>
                  <Link href="/blog" className={linkClassName}>Blog</Link>
                  <Link
                      className={linkClassName}

                      href="/about">About</Link>
                </nav>
                <ModeToggle />

              </div>
            </header>
            <main>{children}</main>
            <Footer/>
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  )
}
